### ISSUE TITLE
Errors during stacker clean: problem cleaning roots

### ISSUE THREAD

**Issue by smoser** [anuvu/stacker#136] opened 2021-02-24 19:35 UTC
```
$ stacker --version
stacker version v0.5.0-312-g3cdc636

$ bdir=$PWD/build
$ stacker --storage-type=overlay --oci-dir=$bdir/oci --roots-dir=$bdir/roots --stacker-dir=$bdir/stacker build
using storage backend overlay
preparing image build-env...
downloading https://dl-cdn.alpinelinux.org/alpine/v3.13/releases/x86_64/alpine-minirootfs-3.13.2-x86_64.tar.gz
2.60 MiB / 2.60 MiB [----------------------------------------------------------------------------] 100.00% 718.17 KiB p/s
+ echo hi world.
hi world.
+ chmod ugo-w /etc
preparing image runtime...
+ ls -ld /etc
dr-xr-xr-x   15 root     root          4096 Feb 24 19:32 /etc

$ stacker --storage-type=overlay --oci-dir=$bdir/oci --roots-dir=$bdir/roots --stacker-dir=$bdir/stacker clean
using storage backend overlay
problem cleaning roots couldn't clean rootfs dir: unlinkat /tmp/x/build/roots/build-env/overlay/etc/fstab: permission den
ied
problem cleaning roots unlinkat /tmp/x/build/roots/build-env/overlay/etc/fstab: permission denied
error: cleaning failed
```

stacker.yaml is:
```yaml
build-env:
  build_only: true
  from:
    type: tar
    url: https://dl-cdn.alpinelinux.org/alpine/v3.13/releases/x86_64/alpine-minirootfs-3.13.2-x86_64.tar.gz
  run: |
    echo hi world.
    chmod ugo-w /etc

runtime:
  build_only: true
  from:
    type: built
    tag: build-env
  run: |
    ls -ld /etc
```

**Comment by tych0** [comment] 2021-02-25 15:39
I suppose this is mostly a dupe of #111 in that we need to run clean() in the same userns that we run the builds in so it can actually delete 000 files and other strange things. We can add another internal_go.go redirect hack if it's causing a lot of pain, though.

**Comment by tych0** [comment] 2021-03-05 18:01
Heh, I think this is an actual dupe of #116, so I'll go ahead and close it :)

**Closed by tych0** 2021-03-05 18:01 UTC
