### ISSUE TITLE
crash in stacker.copyBuiltTypeBaseToOutput

### ISSUE THREAD

**Issue by mikemccracken** [anuvu/stacker#97] opened 2020-07-21 07:08 UTC
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbfcbed]
goroutine 1 [running]:
github.com/anuvu/stacker.copyBuiltTypeBaseToOutput(0x7ffd77c19516, 0x24, 0x7ffd77c19545, 0x20, 0x7ffd77c19572, 0x22, 0x0, 0xe012e9, 0x5, 0xc0003abd70, ...)
/root/go/src/github.com/anuvu/stacker/base.go:248+0x7ad
github.com/anuvu/stacker.SetupRootfs(0x7ffd77c19516, 0x24, 0x7ffd77c19545, 0x20, 0x7ffd77c19572, 0x22, 0x0, 0xe012e9, 0x5, 0xc0003abd70, ...)
/root/go/src/github.com/anuvu/stacker/base.go:86+0x561
github.com/anuvu/stacker.(*Builder).Build(0xc000b2f3e0, 0xc0003d7c20, 0x29, 0x0, 0x0)
/root/go/src/github.com/anuvu/stacker/build.go:199+0xe2a
github.com/anuvu/stacker.(*Builder).BuildMultiple(0xc000b2f3e0, 0xc00026b3f0, 0x1, 0x1, 0x12, 0x7ffd77c19572)
/root/go/src/github.com/anuvu/stacker/build.go:539+0x502
main.doBuild(0xc00020e160, 0x0, 0x0)
/root/go/src/github.com/anuvu/stacker/cmd/build.go:99+0x148
github.com/urfave/cli.HandleAction(0xcc3380, 0xe48870, 0xc00020e160, 0xc00020e160, 0x0)
/root/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526+0xbe
github.com/urfave/cli.Command.Run(0xe012ee, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe2b611, 0x2f, 0x0, ...)
/root/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174+0x528
github.com/urfave/cli.(*App).Run(0xc0001fc000, 0xc0000f4000, 0xf, 0xf, 0x0, 0x0)
/root/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:279+0x731
main.main()
/root/go/src/github.com/anuvu/stacker/cmd/main.go:204+0xb8e
```

**Comment by rnataraja** [comment] 2020-07-21 18:21
This issue is due to following stacker file, It is definitely wrong. First timewhen godev is not built it throws an unrelated error message.  Then I tried building godev layer and after it is finished, run the this stacker again. It will crash. 


config:
  prerequisites:
    - ../godev/stacker.yaml

build-minio:
  from:
    type: built
    tag: godev
  run: |
    cd /root
    export GO111MODULE=on        # force use of go modules
    export GOCACHE=/root/go/.cache # enabling caching modules
    export GOPATH=/root/go         # also needed for caching
    git clone https://github.com/minio/minio.git /root/go/src/github.com/minio/minio
    cd /root/go/src/github.com/minio/minio 
    git checkout RELEASE.2020-07-20T02-25-16Z
    make
    cp minio /root/minio.bin
  build_only: true

config:
  prerequisites:
    - ../base/stacker.yaml
  from:
    type: built
    tag: base
  import:
    - stacker://build-minio/root/minio.bin
  run: |
    cp /stacker/minio.bin /bin/minio

    # clean unnecesary data
    /usr/local/bin/oci-clean

**Comment by tych0** [comment] 2020-07-27 13:22
What version is this? The line numbers don't match up with current git master, unfortunately :(

**Comment by tych0** [comment] 2020-07-27 19:24
Can you post a complete example that fails? I can't seem to reproduce this.

**Comment by tych0** [comment] 2020-07-27 20:18
So I think the underlying problem here was a typo in the file (it sounds like) combined with an assumption we made in how prerequisites work. I've just pushed a fix that closes this with a better error message, but let's re-open if there's a real bug in the resolution of things somehow.

**Closed** 2020-07-27 20:18 UTC
